name: CI

on: [push, pull_request]

jobs:
  test:
    name: >-
      Test (${{ matrix.gemfile }} ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
        - gemfiles/rails_5.0.gemfile
        - gemfiles/rails_5.1.gemfile
        - gemfiles/rails_5.2.gemfile
        - Gemfile
        ruby:
        - 2.3
        - 2.4
        - 2.5
        - 2.6
        - 2.7
        - jruby
        include:
        - ruby: 2.3
          gemfile: 'gemfiles/rails_4.0.gemfile'
        - ruby: 2.3
          gemfile: 'gemfiles/rails_4.1.gemfile'
        - ruby: 2.3
          gemfile: 'gemfiles/rails_4.2.gemfile'
        - ruby: 2.6
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.7
          gemfile: gemfiles/rails_head.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
